export const CAMPSITES_LOADING = 'CAMPSITES_LOADING';
export const ADD_CAMPSITES = 'ADD_CAMPSITES';
export const CAMPSITES_FAILED = 'CAMPSITES_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const POPULARS_LOADING = 'POPULARS_LOADING';
export const ADD_POPULARS = 'ADD_POPULARS';
export const POPULARS_FAILED = 'POPULARS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';

export const ADD_COMMENT = 'ADD_COMMENT';

export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 

export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const INGREDIENTS_FAILED = 'INGREDIENTS_FAILED';

export const ADD_INSTRUCTIONS = 'ADD_INSTRUCTIONS';
export const INSTRUCTIONS_FAILED = 'INSTRUCTIONS_FAILED';

export const ADD_THINGS = 'ADD_THINGS';
export const THINGS_FAILED = 'THINGS_FAILED';

export const ADD_DETAILS = 'ADD_DETAILS';
export const DETAILS_FAILED = 'DETAILS_FAILED';